### ISSUE TITLE
API Create blank record

### ISSUE THREAD

**Issue by romuloccomp** [espocrm/documentation#1]
Hi, there.

I've tried to use API Rest in Espocrm, but after POST in Account, Contact and Meeting the fields record create is blank.

I used Firefox Extension http://restclient.net/ for test the rest. 
The auth is ok, I tested.

Current version: 4.0.2 
URL: http://ideiasoftware.com.br/crm/api/v1/Meeting

Post:

```
{
        "name": "Treinamento Inifit",
        "deleted": false,
        "status": "Held",
        "dateStart": "2016-03-04 10:00:00",
        "dateEnd": "2016-03-04 12:00:00",
        "duration": 3600,
        "reminders":
        [
        ],
        "description": "Test from api",
        "createdAt": "2016-03-02 13:20:53",
        "modifiedAt": "2016-03-10 01:59:41",
        "parentId": "56d6e8b306bbc347c",
        "parentType": "Account",
        "parentName": "Infinit Telecom",
        "accountId": "56d6e8b306bbc347c",
        "accountName": "Infinit Telecom",

.......
}
```

Return ok:

```
    {
        "id": "56e0db0e5635efa86",
        "deleted": false,
        "status": "Planned",
        "duration": "3600",
        "createdAt": "2016-03-10 02:25:18",
        "modifiedAt": "2016-03-10 02:25:18",
        "createdById": "1"
    }
```

Screen shot:

![screen shot 2016-03-09 at 11 30 52 pm](https://cloud.githubusercontent.com/assets/498289/13657564/0c26a498-e64f-11e5-9699-c0dff9cf13e6.png)

**Comment by edbatbaz** [comment]
Dude I have problems making the authentication work, would you give me a hand? there's almost nothing here to work with

**Comment by yurikuzn** [comment]
You need to pass record data in Request Payload.

**Comment by edbatbaz** [comment]
Thanks Yuri, according to me I already did but it sends me an OK response

![image](https://user-images.githubusercontent.com/16905756/29831065-98fa7348-8ca9-11e7-9657-415e540a7537.png)

**Comment by yurikuzn** [comment]
Try to open developer console in your browser (F12 key), then open network tab. Do the action you aim to do throgh API manually (submit form) and check what the request is logged in console. Just replicate that request in your API call. It couldn't be a bug, otherwise espocrm wouldn't work.

The source of application is open. You can always debug.

**Comment by edbatbaz** [comment]
it's trowing me this error on espo log 

[2017-08-29 18:10:47] Espo.ERROR: Uncaught Exception Error: "Cannot unset string offsets" at /home/XXXX/public_html/crm                 /application/Espo/Services/Record.php line 566 {"exception":"[object] (Error(code: 0): Cannot unset string offsets at /home                 /XXXX/public_html/crm/application/Espo/Services/Record.php:566)"} []

the function that is processing that data is as follows
 public function createEntity($data)
    {
        if (!$this->getAcl()->check($this->getEntityType(), 'create')) {
            throw new Forbidden();
        }

        $entity = $this->getRepository()->get();

        $this->filterInput($data);
        $this->handleInput($data);

        **unset($data['modifiedById']);
    **   unset($data['modifiedByName']);
        **unset($data['modifiedAt']);
        **unset($data['createdById']);
        **unset($data['createdByName']);
        **unset($data['createdAt']);**

        $entity->set($data);

        if (!$this->getAcl()->check($entity, 'create')) {
            throw new Forbidden();
        }

        $this->beforeCreate($entity, $data);

        if (!$this->isValid($entity)) {
            throw new BadRequest();
        }

        if (!$this->checkAssignment($entity)) {
            throw new Forbidden('Assignment permission failure');
        }

        $this->processDuplicateCheck($entity, $data);

        if ($this->storeEntity($entity)) {
            $this->afterCreate($entity, $data);
            $this->afterCreateProcessDuplicating($entity, $data);
            $this->prepareEntityForOutput($entity);

            $this->processActionHistoryRecord('create', $entity);

            return $entity;
        }

        throw new Error();
    }

and the JSON sent is:

{ 
            "name": "EDU",
            "deleted": false,
            "website": null,
            "emailAddress": null,
            "phoneNumber": null,
            "type": "",
            "industry": "",
            "sicCode": null,
            "billingAddressStreet": "Calle Mexico 5",
            "billingAddressCity": "Madrid",
            "billingAddressState": null,
            "billingAddressCountry": null,
            "billingAddressPostalCode": "28020",
            "shippingAddressStreet": null,
            "shippingAddressCity": null,
            "shippingAddressState": null,
            "shippingAddressCountry": null,
            "shippingAddressPostalCode": null,
            "description": "1",
            "campaignId": null,      
            "assignedUserId": null,
            "assignedUserName": null
 }

**Comment by yurikuzn** [comment]
Maybe you didn't indicat payload content's type 'application/json'. $data should set with an array derived from parsing json.
