### ISSUE TITLE
Translating into Vietnamese

### ISSUE THREAD

**Issue by chrisli88** [espocrm/documentation#159]
Hello, I'm Vietnamese and i want to help translating this program into Vietnamese

**Comment by yurikuzn** [comment]
Yes. Please create translated files in i18n/vi_VN directory.

**Comment by chrisli88** [comment]
Thanks

**Comment by chrisli88** [comment]
Hi yurikuzn, i have just updated my first translation. Please help check. Thank you

**Comment by yurikuzn** [comment]
You have files that modify original english texts. Please move them to  i18n/vi_VN

**Comment by chrisli88** [comment]
Thank you! Just made another pull request for stream.md. Hope you merge it soon
