### ISSUE TITLE
I have issue with upgrade from 3.9.2 to 4.0.0

### ISSUE THREAD

**Issue by mosaadms** [espocrm/documentation#2]
After upgrade from 3.9.2 to version 4.0.0 the . not working . 

But i got message error 500 in installing  .

and give me this message "Error 404
The url you requested can't be handled."

**Comment by yurikuzn** [comment]
Hi.
Just fix permissions for file index.php

**Comment by mosaadms** [comment]
Dear yurikuzn
 Thank you for your help,  it's working now.
