### ISSUE TITLE
Found an issue in user-guide/emails.md

### ISSUE THREAD

**Issue by chrisli88** [espocrm/documentation#242]
Hi, i found an issue in original emails.md in user-guide when translating. 

> It's possible to use placefolders in email template's body and subject e.g. {Account.name}, {Person.emailAddress}. They will be replaced with values of related records.
> 
> You can use additional reserved placefolders in template body: {optOutUrl} and {optOutLink}.

I think the correct word should be used here is "placeholders", instead of "placefolders".

**Comment by yurikuzn** [comment]
Thanks. Fixed.
