### ISSUE TITLE
Translation of espoCRM documentation into spanish language

### ISSUE THREAD

**Issue by siersod-utopian** [espocrm/documentation#29]
Greetings espoCRM Team!

I would like to help translating the documentation of espoCRM into spanish language. In order to do so, I have a couple of questions.

Should I make a new branch called Spanish and do the translation from there? or how would it be more convenient to have this translation?

Thanks in advance for your answer.

**Comment by yurikuzn** [comment]
Hi,

I'm not sure. Maybe you could start by forking or copying this repository and then we will come up with something.
