### ISSUE TITLE
Install Espocrm in Windows Server 2008, IIS

### ISSUE THREAD

**Issue by mosaadms** [espocrm/documentation#3]
Hi ,
## I tried to install Espocrm in windows server using IIS , but it give me this error

Permission denied for "data" directory. Please set 775 for "data" or just execute this command in the terminal 
cd C:\inetpub\wwwroot\Archive && find data -type d -exec chmod 775 {} +;
Operation not permitted? Try this one: cd C:\inetpub\wwwroot\Archive && find data -type d -exec sudo chmod 775 {} +;

**Comment by tmachyshyn** [comment]
It seems like "data" folder in the EspoCRM root directory is not writable by the IIS server. Please check it. If it doesn't help, please let me know what PHP version do you use?

**Comment by mosaadms** [comment]
Yes, this issue came from folder permission, it's working now .
But I have other issue, I can't upload any file , when I  try to do that give me error 405 . 
thank your advice

**Comment by smejico** [comment]
mosaadms were you able to get this working on your windows server?  I am trying to install on Windows Server 2012 with IIS and having issues?

**Comment by mosaadms** [comment]
I have done that , it's working now , only I have one issue in the "Espo"  didn't accept to upload any file , I think it also permissions issue , in MySQL database
