### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by dbucci24** [espocrm/documentation#316]
..

**Comment by azarus** [comment]
https://en.wikipedia.org/wiki/Caps_lock

**Comment by dbucci24** [comment]
https://en.wikipedia.org/wiki/Autism

**Comment by anaufalm** [comment]
Helo, This file has been translated to spanish. You can see in this [path](https://github.com/espocrm/documentation/tree/master/i18n/es_ES)

**Comment by dbucci24** [comment]
ok, thank you :(
