### ISSUE TITLE
Docomentation: Translation into Spanish Language

### ISSUE THREAD

**Issue by michaelizer** [espocrm/documentation#33]
Greetings, I would like to help you translate all the documentation into Spanish so people limited by the language can still involve into the project. Let me know what do you think.

By the way, should I make a new branch named 'Spanish translations' or something?. Thanks

**Comment by yurikuzn** [comment]
Hi,

We have es_ES directory https://github.com/espocrm/documentation/tree/master/i18n/es_ES. @siersod-utopian contributed already into translation. You could join. 

Thank you.

**Comment by siersod-utopian** [comment]
to avoid that we work in the same file at the same time and translate 2 times the same thing, start to translate from the development folder, or the user guide folder.

**Comment by michaelizer** [comment]
@yurikuzn @siersod-utopian Understood (Y)

**Comment by fucho18** [comment]
how can I know what is already translated?
