### ISSUE TITLE
I can't upload in file , give me error 405

### ISSUE THREAD

**Issue by mosaadms** [espocrm/documentation#4]
I can't upload any file , when I  try to do that give me error 405 . 
thank your advice
"PHP Warning:  mkdir(): Permission denied in C:\inetpub\wwwroot\Archive\application\Espo\Core\Utils\File\Manager.php on line 405"

**Comment by yurikuzn** [comment]
Check permissions for /data/upload directory

**Comment by mosaadms** [comment]
Hi ,
There's not issue with the permission I have checked it ,
And I found all file I tried to upload their (Upload folder) as the image
below :


[image: Inline image 1]
[image: Inline image 2]
​

On Thu, May 19, 2016 at 3:32 PM, Yuri Kuznetsov <notifications@github.com>
wrote:

> Check permissions for /data/upload directory
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/espocrm/documentation/issues/4#issuecomment-220298614>
>



-- 
--------------------
*Mosaad ElSayed Abdulghaffar*
*Mob *: +971555577014
*P.O.Box* : 27433 Sharjah. UAE
*Email :* Mosaad <Mosaadms@scfa.ae>g@gmail.com
--------------------------------------------------------
