### ISSUE TITLE
Nginx configuration?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [espocrm/documentation#5]
I saw that you mention continuously that EspoCRM can be installed on Nginx too, but I see no official documentation about the `.conf` file parts that needs to be there.

Googling a little, I found only this result which I didn't test honestly: https://www.rosehosting.com/blog/how-to-install-espocrm-with-nginx-on-an-ubuntu-vps/

Can you please maybe offer an official version for it?

Thanks in advance!

**Comment by yurikuzn** [comment]
We didn't test it too. We're going to write documentation in future.

**Comment by julianxhokaxhiu** [comment]
How long the future will be? I would like to install it on the company where I'm working, but I'll be here only for a short time. Your Software is a potential candidate but I only need the Nginx configuration.

**Comment by yurikuzn** [comment]
Unfortunately can't do it soon. You can try the documentation that you found.

**Comment by krisgermann** [comment]
I've tried that link above, I'm getting a "Bad Server Response" message on a fresh install (however I'm still attempting to troubleshoot... could be my mistake).

**Comment by julianxhokaxhiu** [comment]
Honestly I'm not even trying...unless it's not official and supported it makes no sense.

The question is why is it taking so long to just write a tested configuration?

**Comment by yurikuzn** [comment]
Because we are not supermans but usually busy as beavers. It's Open Source project and we would be happy if people helped us event with such thing as configuration.

**Comment by julianxhokaxhiu** [comment]
I didn't want to sound rude. Sorry.

Although I feel confident that even if I convert the `.htaccess` to a valid configuration for nginx, I'm sure that I'll maybe miss something important but given as "default" logic on Apache.

That's why I was asking that if possible to have at least a valid starter from you, which can later evolve even from the community, even from me, myself.

**Comment by yurikuzn** [comment]
I'd like to help but I'm not a specialist in this area. It was supposed that all needed information regarding congifuration should show up during installation process. We are going to tackle this issue once we get time.

**Comment by karljohns0n** [comment]
I followed the URL in the first post to setup nginx for EspoCRM. Everything is fine except that I get "Connection reset by peer" on most GET/POST on /api/v1/, exemple:

`2016/05/16 13:35:40 [error] 10673#10673: *43 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.6.194, server: crm.git, request: "GET /api/v1/Activities/action/popupNotifications HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "crm.git", referrer: "http://crm.git/"`

`2016/05/16 13:34:00 [error] 10033#10033: *4755 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.6.132, server: crm.git., request: "GET /api/v1/Notification/action/notReadCount HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "crm.git.", referrer: "http://crm.git./"`

I use the code in first URL tutorial:

```bash
location /api/v1/ {
        if (!-e $request_filename){
	        rewrite ^/api/v1/(.*)$ /api/v1/index.php last; break;
        }
}
```

Anything wrong with this block?

**Comment by julianxhokaxhiu** [comment]
I saw that now the configuration is there :) Very nice! https://www.espocrm.com/documentation/administration/nginx-server-configuration/
