### ISSUE TITLE
pleas

### ISSUE THREAD

**Issue by calvin7** [espocrm/documentation#504]
Dear to : Project owner
Excuse me, I would like to translate in your project into Russian, if you are willing to let me contribute to your project.

**Comment by yurikuzn** [comment]
Добрый день,
можно. но большинство материалов уже переведено https://github.com/espocrm/documentation/tree/master/i18n/ru_RU

**Comment by calvin7** [comment]
Хороший день назад, спасибо, что позволил мне перевести его, спасибо :)
