### ISSUE TITLE
Clarify when API token gets invalidated

### ISSUE THREAD

**Issue by dransome** [espocrm/documentation#541]
https://github.com/espocrm/documentation/blob/master/development/api.md states:
> or token is not valid anymore

Please can you elaborate why/when/how a token might be invalidated?

I would like to create an API token for my API script to use, but I am worried that it might 'randomly' encounter this 401 error due to the token becoming invalidated. This is just for a "quick and dirty" script, so I don't really want to implement code to handle that situation if the conditions that cause token invalidation will not apply...

**Comment by yurikuzn** [comment]
The most of auth logic is processes here: https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Auth.php

You can debug.

**Comment by dransome** [comment]
Ok, well for example I see https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Auth.php#L302 probably invalidates the token, but can you give some pointers what calls that function? (I couldn't find any cases where destroyToken is called within Auth.php)

**Comment by tanyalei** [comment]
https://github.com/espocrm/espocrm/blob/master/application/Espo/Controllers/App.php#L48
https://github.com/espocrm/espocrm/blob/master/client/src/app.js#L483

**Comment by tanyalei** [comment]
and if timeout, according to auth settings
https://github.com/espocrm/espocrm/blob/master/application/Espo/Jobs/AuthTokenControl.php

or situations, when we set ("isActive", false) in https://github.com/espocrm/espocrm/blob/master/application/Espo/Core/Utils/Auth.php

**Comment by dransome** [comment]
Hmm, I see. So basically any script that interacts with API needs to know user/password (can't just generate a token and leave it to use that), so it can generate its own token at the start of each execution (and handle any possible 401 response).

API is not really usable for my use case then.

Thanks for your help / clarifications.

**Comment by tanyalei** [comment]
If you have no limits by time and don't check the box Only one auth token per user, you can use for API your once generated token.

**Comment by yurikuzn** [comment]
You can create a separate user with restricted rights and use it for API access. What's the problem to store password.
