### ISSUE TITLE
Clarify when 'EspoClient: Unknown Error'

### ISSUE THREAD

**Issue by romulocomin** [espocrm/documentation#573]
The message "Uncaught exception 'Exception' with message 'EspoClient: Unknown Error' in "

the response code is 200, but i receive this message when i just try your example

$client = new EspoApiClient('https://your-espocrm-site', 'USERNAME', 'PASSWORD');

$response = $client->request('POST', 'Lead', [
    'firstName' => 'Test',
    'lastName' => 'Hello'
]);

This message does not make the error very clear

**Comment by yurikuzn** [comment]
I tried and it worked fine. Check your logs.
