### ISSUE TITLE
How to make a GET request for modifiedAt after a specifict datetime?

### ISSUE THREAD

**Issue by lutzhorn** [espocrm/documentation#6]
I've found that `?where[0][field]=somefield&where[0][type]=equals&where[0][value]=somevalue` can be used to make a request for equality. But how can I query on a datetime field like `modifiedAt`? I'd like to query for all entities that have been modified after a specific datetime. How can this be done?

Is there a complete documentation for the filters that can be used on a GET request? How are the query parameters that build a filter to be used?

**Comment by yurikuzn** [comment]
Try to make such a search in EspoCRM and look to browser console what GET request is being sent.

**Comment by lutzhorn** [comment]
How can I make such a search? I find to form in the web GUI to formulate a filter on a datetime field.

**Comment by yurikuzn** [comment]
Doesn't filtering opportunities by `Created At` field suit? There is 'After' filter.

**Comment by lutzhorn** [comment]
Ah, I didn't recognize that 'Add field' means 'Add a search condition'.
