### ISSUE TITLE
Translations into indonesian language

### ISSUE THREAD

**Issue by yhandot** [espocrm/documentation#61]
Hello team EspoCRM ,
I am translator indonesian language , i want to help your project to translate espoCRM into indonesian language , thank you for your attention, 

Regard

**Comment by yurikuzn** [comment]
Hi,

Appreciate your endeavour. Could you please create translated files in https://github.com/espocrm/documentation/tree/master/i18n/id_ID directory.

Please don't modify original files.

**Comment by yhandot** [comment]
This is already translate by other people , thanks

**Comment by yhandot** [comment]
I am already translate but i am not sure this is correct or not, can you check ?

**Comment by kilkl** [comment]
I am here to translate project
