### ISSUE TITLE
Filipino Translation

### ISSUE THREAD

**Issue by burdagay** [espocrm/documentation#62]
Hi there. Can I add Filipino translations to your docs? I'd really like to contribute so that other Filipinos may discover and use this awesome project as well.

**Comment by tanyalei** [comment]
Hi,
yes, you can.
Your translation has to be in /i18n/fil_PH with the same structure as the main documentation.

**Comment by burdagay** [comment]
Thank you!

**Comment by burdagay** [comment]
I'll also do a Cebuano translation since I can also speak it. Thanks again!
