### ISSUE TITLE
workflow : trigger onchange billing address not available

### ISSUE THREAD

**Issue by relyd** [espocrm/documentation#659]
Use case : send Email with old and new billing address when billing address did change.
 
Entity : account

**Issue** : billing address elements are not available in fieldlist
Tried workaround : using formula  entity\isAttributeChanged(billingAddressPostalCode) || .. 
but this does not trigger after updating the record. 

Version 5.7.11

**Comment by yurikuzn** [comment]
Workflow is out of scope of this repository.
