### ISSUE TITLE
additional info

### ISSUE THREAD

**Issue by analystcmyk** [espocrm/documentation#662]
- suggest to add link to "how to upgrade extensions", or explain that this is part of the knowledgebase in the portal
- suggest to be explicit if it is allowed to jump from 1.03 -> 1.05 directly, skipping 1.04

**Comment by yurikuzn** [comment]
Do you mean this https://github.com/espocrm/documentation/blob/master/administration/extensions.md#how-to-upgrade-an-extension ?

**Comment by analystcmyk** [comment]
Yes, that one is better than the instructions in the knowledgebase, maybe just add pointer.

Clarification: it is not clear if you must perform 1.3->1.4->1.5 or if you can skip an intermediate version.

**Comment by yurikuzn** [comment]
Done.
