### ISSUE TITLE
Requesting for Tagalog or Cebuano Translation

### ISSUE THREAD

**Issue by cortesclintmark** [espocrm/documentation#67]
Hi,  I would like to open translation for Tagalog or Cebuano. I willing to contribute for this project using our own languageand also to introduce this project to my fellow Filipino people.

**Comment by tanyalei** [comment]
Hi
Your translation has to be in /i18n/ceb_PH for Cebuano or in /i18n/tl_PH for Tagalog with the same structure as the main documentation.
Thanks

**Comment by cortesclintmark** [comment]
Thank you so much. Lastly, there no link for this maam?

**Comment by yhandot** [comment]
You can to go there now
https://github.com/espocrm/documentation/tree/master/i18n/tl_PH

**Comment by yhandot** [comment]
Sorry i was wrong

**Comment by cortesclintmark** [comment]
No page found Sir.

**Comment by cortesclintmark** [comment]
@yurikuzn Sir, I have something to ask where should i find the file to bw translated?

**Comment by cortesclintmark** [comment]
In filipino or tagalog?
