### ISSUE TITLE
Gmail Oauth panel does not show up for gmail account

### ISSUE THREAD

**Issue by ht512512** [espocrm/documentation#687]
OS: Ubuntu 20.04.1 LTS
Browser: Firefox, Chrome
EspoCRM: 5.9.4 (Running in local docker)

I set up Personal Email Account using a gmail address and saved the account. As per the docs (https://docs.espocrm.com/extensions/google-integration/gmail/), a panel on the right should allow me to authenticate with gmail server using OAuth, but there was no such panel after 'Save', just the block showing Assigned User, Created and Modified. 

I have attached the screenshot below.
![image](https://user-images.githubusercontent.com/3441504/103062714-e6220480-4563-11eb-8ced-36d889886b6f.png)

Thanks,
Hemant

**Comment by yurikuzn** [comment]
Hi,

Please use the customer portal. This repository does not include gmail extension.
