### ISSUE TITLE
Add a new client implementation to the docs

### ISSUE THREAD

**Issue by TheDutchMC** [espocrm/documentation#700]
Hi there!

Over the last week I've been working on a port of the exiting PHP API client to Rust. It is basically done now, and working.
Is there any sort of process to add this client to the list of client implementations [here](https://docs.espocrm.com/development/api/)? By adding it, Rust users will be easily be able to get started on a project that interfaces with EspoCRM, without having to deal with the hassle of searching for an API implementation themselves, or creating one like I did.

The library is currently already available on [crates.io](https://crates.io/crates/espocrm-rs).

Thanks

**Comment by yurikuzn** [comment]
Hi,

Cool. Thanks for your work. You can create a PR to this repository with a file `api-client-rust.md` in this directory https://github.com/espocrm/documentation/tree/master/docs/development.

Links are here: https://github.com/espocrm/documentation/blob/master/docs/development/api.md#client-implementations

**Comment by TheDutchMC** [comment]
Awesome!

I've opened the PR #701
