### ISSUE TITLE
How to download files from backend API?

### ISSUE THREAD

**Issue by csmicfool** [espocrm/documentation#708]
Hi all, seeking some advise please.

I have an application which is a dashboard and external document portal, extending an instance of a CRM.

When I call through the API to get files, it works just fine in Postman, but I'm not sure how to store the file correctly as PHP treats my assignment as a failure:

`if($file = $client->request('GET', 'Attachment/file/'.$document['fileId'], $filename)){
	echo "test";
}`

The code inside the if statement is never executed.

![image](https://user-images.githubusercontent.com/27876324/130448353-9bbf3117-79ab-4fde-82ab-c833e2aaa0d4.png)

**Comment by yurikuzn** [comment]
Please use our forum for help.

**Comment by csmicfool** [comment]
Sorry, I didn't know there is a forum - can you please provide a link?  I didn't see it on the project website.
