### ISSUE TITLE
Duplicate Phone Entry

### ISSUE THREAD

**Issue by czcpf** [espocrm/documentation#732]
Issue: An account cannot have a duplicate entry for different phone_number types
Steps to reproduce:
1. Create a new account
2. Edit the Phone Entry
3. Specify for example as below (ie. CRM wants to be able to specify an Office Number and a Billing Number, which may or may not be the same:
<img width="769" alt="Screen Shot 2022-08-12 at 8 10 59 PM" src="https://user-images.githubusercontent.com/88215293/184462905-30f06a70-8459-4fd8-b214-dc267687e141.png">

**Comment by yurikuzn** [comment]
Not a bug. Not possible by design.

**Comment by czcpf** [comment]
Ok, but please consider that, the 3-column unique requirement in your database table `entity_phone_number` referring to this design choice uses:

UNIQUE requirement for `entity_id`, `phone_number_id`, `entity_type`

I assume `phone_number_id` is a relation to the primary `id` key in table `phone_number` through some model logic in your application.

This choice seems strange to me given that the GUI is complaining about uniqueness of fields:
`numeric`, `type` of table `phone_number`,
where `numeric` is the actual phone number typed-in, and `type` is (ie. mobile,other,main, etc.)

That is, to say, a given (entity_id, entity_type combination) should not have a duplicate (phone_number, phone type)  field such that for example:
a phone number could not be entered as: mobile:123456789, mobile:123456789. Which is a reasonable design choice. However, ‘mobile’ is the ‘type’ of phone number for requirement and has nothing to do with the entity_type.  Is `id` in table `phone_number`  somehow being generated off of (`numeric`,`entity_type`,`entity_id`) ?  If so, I believe this is a bug because this field should either have been primary auto-increment or generated from (`numeric`,`entity_type`,`entity_id`,`type`)

Please also consider that it is common for an office to use the same number for “billing” and “main” for example. So while I can reasonably understand the design requirement to not allow the same ‘type+phone number’ to be duplicated as in the example above, I don’t quite understand why CRM is restricted to not be able to have same phone number for two different types as in the example I provided you.

Mobile: 1234567
Office: 1234567

In order to be able to design CRM front end to accommodate this, the end user has to create an entirely new entity phone field.


On Aug 13, 2022, at 1:12 AM, Yuri Kuznetsov ***@***.***> wrote:
﻿

Not a bug. Not possible by design.

**Comment by yurikuzn** [comment]
Unique index has nothing to do with this, the restricting design coded, not in database. It was designed that phone number is unique, and we was OK with it for 9 years. It would be too much of effort to re-design it now, and we have hundreds of issues in our TODO list.

**Comment by czcpf** [comment]
Understood. Thank you. The application is wonderful and I appreciate the team’s time and effort.

**Comment by yurikuzn** [comment]
Thanks. The next version will raise the application to the next level. A lot of improvements in security and in the theme framework.
