### ISSUE TITLE
Administration > Settings > Activities does not seem to exist

### ISSUE THREAD

**Issue by ZeroEcks** [espocrm/documentation#811]
https://docs.espocrm.com/user-guide/activities-and-calendar/

This page references "Then at Administration > Settings > Activities it's possible to set this entity type as an Activity and make it available in Calendar"

I would like to do this however I absolutely cannot for the life of me find this menu. It does not seem to exist, I had a dig into the changelogs to try and find if it was moved or renamed but still cannot find this functionality

Would it be possible to have the docs updated (and also let me know how to add a custom activity such as "send text message")

Thanks!

**Comment by yurikuzn** [comment]
Maybe you have a customized settings page layout. From the demo:

![image](https://github.com/espocrm/documentation/assets/1006792/d3a03251-f403-40f8-9d42-c8ccf7ed595a)
![image](https://github.com/espocrm/documentation/assets/1006792/a02c9432-f3c1-44a2-bdef-a3fa40ca6147)

**Comment by ZeroEcks** [comment]
Yep user error, I assumed the Administration top level was "settings" then was looking for "Calendar Entity List" in the top level "Administration" menu. Thank you for the quick response mate!
