### ISSUE TITLE
Please update the documentation to explain how to create ES6 front-end files

### ISSUE THREAD

**Issue by bandtank** [espocrm/documentation#813]
I posted about [this issue on the forums](https://forum.espocrm.com/forum/developer-help/97890-custom-es6-controller-cannot-use-import-statement-outside-a-module). In short, the documentation shows the older method of creating front-end files. Please update the documentation so developers can learn how to create ES6 files. Specifically, the documentation for [controllers](https://docs.espocrm.com/development/frontend/controller/) and [views](https://docs.espocrm.com/development/view/) is the most important.

**Comment by yurikuzn** [comment]
You cannot use it unless you [build](https://github.com/espocrm/ext-template#using-es-modules) an entire Espo module into a bundle. If we change docs to ES6 there will be a lot of confusion and questions. Better not to do it now.

**Comment by bandtank** [comment]
That is what I am using. If you could please put instructions somewhere, it would make this a lot easier to figure out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yurikuzn** [comment]
Instructions in the link I posted.

**Comment by yurikuzn** [comment]
You controller code should work if you bundle your module. The only limitation is that you should not put whitespaces or tabs before "import" and "export" statements.

You can import from other Espo modules this way:

```js
import MyView from 'modules/my-espo-module/my-view`;
```

**Comment by bandtank** [comment]
Unfortunately, it is not working for me. Here is what I did:
* git clone git@github.com:espocrm/ext-template.git test
* cd test
* vi extension.json
  * set bundled to true
* vi src/files/custom/Espo/Modules/MyModuleName/Resources/module.json
  * set bundled to true
  * set jsTranspiled to true 
* vi src/files/custom/Espo/Modules/Test/Resources/metadata/app/client.json
* php init.php
  * extension name: "Test"
  * description: "test description"
  * author: "test name"
* mkdir -p src/files/custom/Espo/Modules/Test/Resources/metadata/app
* vi src/files/custom/Espo/Modules/Test/Resources/metadata/app/client.json
  * Paste the following:
 ```
{
  "scriptList": [
    "__APPEND__",
    "client/custom/modules/test/lib/init.js"
  ]
}
```
* npm install
* node build --all

Here is what happened:
```
Fetching EspoCRM repository...
  Downloading EspoCRM archive from Github...
  Unzipping...
Installing EspoCRM instance...
  Creating config...
  Npm install...
  Building...
  Install: step1...
  Install: setupConfirmation...
  Install: checkPermission...
  Install: saveSettings...
  Install: buildDatabase...
  Install: createUser...
  Install: finish...
  Merge configs...
Transpiling...
Copying extension to EspoCRM instance...
node:fs:1583
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/Users/anthony.andriano/Repositories/test/build/assets/transpiled/custom/modules/test/src'
    at Object.statSync (node:fs:1583:3)
    at Object.statSync (/Users/anthony.andriano/Repositories/test/node_modules/graceful-fs/polyfills.js:318:34)
    at statSync (/Users/anthony.andriano/Repositories/test/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/Users/anthony.andriano/Repositories/test/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/Users/anthony.andriano/Repositories/test/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/Users/anthony.andriano/Repositories/test/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at file:///Users/anthony.andriano/Repositories/test/node_modules/espo-extension-tools/build.js:279:20
    at new Promise (<anonymous>)
    at file:///Users/anthony.andriano/Repositories/test/node_modules/espo-extension-tools/build.js:260:9 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/anthony.andriano/Repositories/test/build/assets/transpiled/custom/modules/test/src'
}
```

**Comment by yurikuzn** [comment]
According the error, it needs having the directory `build/assets/transpiled/custom/modules/test/src` existing.

**Comment by yurikuzn** [comment]
Maybe because there was no any file to transpile, it didn't created the directory.

**Comment by bandtank** [comment]
It seems to be working. I created the following files:

**Controller**
`src/files/client/custom/modules/test/src/controllers/calendar2.js`
```
import CalendarController from 'modules/crm/controllers/calendar';

class Calendar2Controller extends CalendarController {
  actionHello(options) {
    console.log("got here")
  }
}

export default Calendar2Controller;
```

**Route**
`src/files/custom/Espo/Modules/Test/Resources/metadata/clientDefs/Calendar2.json`
```
{
  "controller": "test:controllers/calendar2"
}
```

After building, these are the files:
![image](https://github.com/espocrm/documentation/assets/1170415/b2c5de59-2766-4497-8500-0ecfa64f46a6)

I will let you know if I run into any other issues. Thanks for your help.
