### ISSUE TITLE
Nginx Regex

### ISSUE THREAD

**Issue by aldisaglobal** [espocrm/documentation#848]
In the file:
`docs/administration/nginx-server-configuration.md`

This nginx conf snippet has a regex problem.
```
location /client {
        root /path-to-espo; # path to espocrm root dir
        autoindex off;

        location ~* ^.+.(js|css|png|jpg|svg|svgz|jpeg|gif|ico|tpl)$ {
            access_log off;
            expires max;
        }
    }
```

Although it will work as is, the dot "." character should be escaped.
`location ~* ^.+\.(js|css|png|jpg|svg|svgz|jpeg|gif|ico|tpl)$`

**Comment by yurikuzn** [comment]
Fixed. Thanks for reporting.
